spring:
  application:
    name: msvc-image
  cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    api_secret: ${CLOUDINARY_API_SECRET}
  config:
    import: optional:configserver:http://localhost:8888