eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: http://localhost:9091
          predicates:
            - Path=/api/product/**
        - id: inventories
          uri: http://localhost:9092
          predicates:
            - Path=/api/inventory/**
        - id: categories
          uri: http://localhost:9093
          predicates:
            - Path=/api/category/**
        - id: images
          uri: http://localhost:9094
          predicates:
            - Path=/api/image/**